wandb_version: 1

epochs:
  desc: null
  value: 15
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717415774
    t:
      1:
      - 1
      - 5
      - 29
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 29
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
